version: "3.8"

services:
  event-tracker:
    build: .
    container_name: event-tracker
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json
      - ./db.json:/app/db.json
