services:
  event-tracker:
    image: ghcr.io/ammiratafabiano/event-tracker:latest
    container_name: event-tracker
    restart: unless-stopped
    volumes:
      - ./event-tracker/config.json:/app/config.json
      - ./event-tracker/db.json:/app/db.json
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
